name: Rust-CI Action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      # matrix上下文，包含在工作流中定义的应用于当前作业的矩阵属性
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            app: onnxbench_linux_x86_64
          - build: linux
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            app: onnxbench_linux_aarch64
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
            app: onnxbench_macos_x86_64
          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
            app: onnxbench_x86_64.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test
      - name: Build release
        run: cargo build --release
      - name: Upload release build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.build}}-${{matrix.app}}
          path: target/release/${{matrix.app}}
      - name: Create github release
        id: new_release
        uses: softprops/action-gh-release@v2
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GH_TOKEN }}
          make_latest: true
          files: target/release/${{matrix.app}}
